### ISSUE TITLE
Favour StringBuilder over String concat in query building

### ISSUE THREAD

**Issue by retronym** [Jacoby6000/scoobie#35]
In https://github.com/Jacoby6000/scoobie/blob/57067f746a479e0bf3096040cba0a0dab4f58e41/postgres/src/main/scala/scoobie/doobie/postgres/postgres.scala#L42-L63, and related, consider using a mutable `StringBuilder` over string concatenation to reduce GC pressure.

**Comment by Jacoby6000** [comment]
This is no longer relevant as of #43. We're now using semigroupal appends for query concatenation.  GC pressure is still a concern, but there's no easy win as there was previously.
