### ISSUE TITLE
Doobie 0.3.1 support

### ISSUE THREAD

**Issue by Daenyth** [Jacoby6000/scoobie#42]
Does scoobie work with Doobie 0.3.1? As I understand it, a fair amount changed, but I'm not sure how heavily it impacts you

**Comment by Jacoby6000** [comment]
I can add in Doobie 0.3.1 support relatively easily. The doobie support classes are very simple.  I'll try to find some time to do it this week. I didn't know anybody even looked at this project!

**Comment by Jacoby6000** [comment]
I know this is a bit late.. like a month and a half late. But I'm getting in doobie 4.0 and 4.1 support today.  If you still want doobie 3.x support I can add it in, but it seems like tpolecat has marked 3.1 as EOL.

**Comment by Jacoby6000** [comment]
Seems like there are some significant breaking changes from 3.x to 4.x, so maybe not tonight. I need to look in to properly integrating with the new doobie `Fragment` api. This should make the compatibility layer much less hacky than it was previously.

**Comment by Daenyth** [comment]
I don't need 0.3.1, 0.4.x is fine.

**Comment by Jacoby6000** [comment]
Skipping over 0.3.1.  #43 will add 0.4.x support
